### PR TITLE
Fix mypy errors

### PR DESCRIPTION
**Pull request by leo-gan**
- Fixed type errors found by the `mypy`.
- Sorted imports with `isort`.
- Removed unused args in the `_get_entries_path`, `_get_class_ids_path`, `_get_class_names_path`
- Added missed requirements (`PLW`, which gets `numpy`, `setuptools`)
- Added missed versions to some requirements.
- Added `exclude = venv` to `setup.cfg`

**NOTE:** Please check comments marked with `LG TODO`. I'm not sure how to fix these errors.

### CODE REVIEW

**Comment by leo-gan** [comment]
Can anybody review this, please? :)

**Comment by leo-gan** [comment]
Anybody here???

**Comment by leo-gan** [comment]
@patricklabatut Please, review it.

**Comment by leo-gan** [comment]
@facebook-github-bot  "We actively welcome your pull requests." - it sounds like a joke. Can anybody, please, review it?

**Comment by patricklabatut** [comment]
Hey @leo-gan,

Each individual change may be simple, this PR is nevertheless still touching a large percentage of the codebase. Also, as you described it, it is mixing a number of different modifications:
- adjustments to project configuration,
- re-ordering imports (BTW, we used to apply isort, but I don't recall now why we ended up disabling it),
- whitespace removal,
- correcting incorrect mypy annotations,
- reducing the number of mypy warnings (sometimes by introducing exceptions).

We sincerely appreciate the efforts and the willingness to contribute. If you want to get this PR reviewed and hopefully merged, I think it would make better sense to split it into simpler and more targeted PRs.

**Comment by leo-gan** [comment]
Closing now. I'll split this PR to several PRs as requested by @patricklabatut

**Pull request closed without merging**
