### PR TITLE
Add new backbones trained with registers

### PR DESCRIPTION
**Pull request by patricklabatut**
Add new backbones (and matching linear classification heads) trained with 4 registers following [Vision Transformers Need Registers](https://arxiv.org/abs/2309.16588).

### CODE REVIEW

**Review by qasfb — APPROVED** [review]

**Comment by mshooter** [comment]
Hi I am getting this error when try to load it from the hub.. 
RuntimeError: Cannot find callable dinov2_vitb14_reg in hubconf

**Comment by patricklabatut** [comment]
> RuntimeError: Cannot find callable dinov2_vitb14_reg in hubconf

If you previously used the provided models via PyTorch Hub before this new release, then an older version of the repo may simply be cached by PyTorch (under `~/.cache/torch/hub`). Try passing `force_reload=True` to `torch.hub.load()` to bypass the cached version (alternatively remove the cached repo under `~/.cache/torch/hub`).

**Comment by mshooter** [comment]
@patricklabatut, the force_reload=True fixed it for me. 
Thank you!

**Comment by maxrohleder** [comment]
Hi @patricklabatut, I have a brief detail question. What was the reason for introducing the option for anti-aliasing in the position encoding interpolation function?
 https://github.com/facebookresearch/dinov2/blob/e1277af2ba9496fbadf7aec6eba56e8d882d1e35/dinov2/models/vision_transformer.py#L203-L208)

As mentioned in this issue https://github.com/facebookresearch/dinov2/issues/468#issuecomment-2488820722 we experienced issues when training a model from scratch without anti aliasing. Did you experience similar problems?

**Pull request merged**
